class Board:
    def __init__(self, rows=8, cols=8): ...
    def get(self, x,y): ...
    def set(self, x,y,piece): ...
    def move(self, fx,fy, tx,ty) -> Move: ...
    def clone(self) -> Board: ...
    def in_bounds(self, x,y) -> bool: ...